[package]
name = "rust-agent-mcp-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

# O SDK MCP entra na fase 6.
